---
swagger: "2.0"
info:
  description: "Trasnparency "
  version: "0.0.0 "
  title: "Transparency"
host: "docs.aintfor.me"
basePath: "/v0"
schemes:
- "https"

paths:
  /users:
    get:
      tags:
        - "User"
      summary: "Returns a list of users."
      produces:
        - "application/json"
      responses:
        200:
          description: "OK!"
  /users/create:
    post:
      tags:
        - "User"
      summary: "Create a user account."
      responses:
        200:
          description: "Ok!"
  /users/{userID}:
    post:
      tags:
        - "User"
      summary: "Create a user account."
      responses:
        200:
          description: "Ok!"
      parameters:
        - in: path
          name: userID
          required: true
          type: integer
          format: int64
          
